### PR TITLE
Feature/homepage: Select API

### PR DESCRIPTION
**Pull request by Zafron047**
- [x]  I have selected the API that will be used for the project.

### CODE REVIEW

**Review by Chandan-devs-tech — CHANGES_REQUESTED** [review]
Hi @Zafron047, 


# Required Changes ♻️ 

- Please fix the Linters issue.

**Comment by Zafron047** [comment]
@Chandan-devs-tech 
Thanks for the review.

- [x] I have fixed the issues. 

_Note: And I have disabled eslint for a specefic line since I have not called the variable just yet. It will not be an error after I call the baseUrl later._

**Review by Chandan-devs-tech — APPROVED** [review]
Hi @Zafron047,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

**Comment by Zafron047** [comment]
@Chandan-devs-tech Thanks for the review. 😄 👍

**Pull request merged**
